const sampleUsers = [
  {
    username: "john_doe",
    email: "john.doe@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-310-555-0101",
    address: {
      streetAddress: "123 Ocean Avenue",
      city: "Malibu",
      pincode: "90265",
      landmark: "Near Malibu Beach",
    },
  },
  {
    username: "emma_wilson",
    email: "emma.wilson@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-212-555-0102",
    address: {
      streetAddress: "45 Broadway",
      city: "New York City",
      pincode: "10006",
      landmark: "Near Wall Street",
    },
  },
  {
    username: "oliver_smith",
    email: "oliver.smith@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-970-555-0103",
    address: {
      streetAddress: "78 Mountain Road",
      city: "Aspen",
      pincode: "81611",
      landmark: "Near Aspen Mountain",
    },
  },
  {
    username: "sophia_martin",
    email: "sophia.martin@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+39-055-555-0104",
    address: {
      streetAddress: "12 Via Roma",
      city: "Florence",
      pincode: "50121",
      landmark: "Near Piazza della Signoria",
    },
  },
  {
    username: "liam_johnson",
    email: "liam.johnson@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-503-555-0105",
    address: {
      streetAddress: "89 Forest Avenue",
      city: "Portland",
      pincode: "97205",
      landmark: "Near Washington Park",
    },
  },
  {
    username: "ava_brown",
    email: "ava.brown@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+52-998-555-0106",
    address: {
      streetAddress: "56 Avenida Kukulkan",
      city: "Cancun",
      pincode: "77500",
      landmark: "Near Hotel Zone",
    },
  },
  {
    username: "noah_davis",
    email: "noah.davis@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-775-555-0107",
    address: {
      streetAddress: "34 Lakeview Drive",
      city: "Lake Tahoe",
      pincode: "96145",
      landmark: "Near Lake Tahoe",
    },
  },
  {
    username: "isabella_miller",
    email: "isabella.miller@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-213-555-0108",
    address: {
      streetAddress: "210 Sunset Boulevard",
      city: "Los Angeles",
      pincode: "90028",
      landmark: "Near Hollywood",
    },
  },
  {
    username: "james_wilson",
    email: "james.wilson@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+41-21-555-0109",
    address: {
      streetAddress: "25 Alpine Road",
      city: "Verbier",
      pincode: "1936",
      landmark: "Near Verbier Ski Resort",
    },
  },
  {
    username: "mia_taylor",
    email: "mia.taylor@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+255-27-555-0110",
    address: {
      streetAddress: "17 Safari Lane",
      city: "Serengeti National Park",
      pincode: "23100",
      landmark: "Near Serengeti Visitor Centre",
    },
  },
  {
    username: "benjamin_anderson",
    email: "benjamin.anderson@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+31-20-555-0111",
    address: {
      streetAddress: "88 Canal Street",
      city: "Amsterdam",
      pincode: "1012",
      landmark: "Near Dam Square",
    },
  },
  {
    username: "charlotte_thomas",
    email: "charlotte.thomas@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+679-555-0112",
    address: {
      streetAddress: "10 Island Road",
      city: "Fiji",
      pincode: "679",
      landmark: "Near Nadi Bay",
    },
  },
  {
    username: "lucas_jackson",
    email: "lucas.jackson@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+44-20-555-0113",
    address: {
      streetAddress: "42 Cotswold Lane",
      city: "Cotswolds",
      pincode: "GL54",
      landmark: "Near Bourton-on-the-Water",
    },
  },
  {
    username: "amelia_white",
    email: "amelia.white@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-617-555-0114",
    address: {
      streetAddress: "76 Beacon Street",
      city: "Boston",
      pincode: "02108",
      landmark: "Near Boston Common",
    },
  },
  {
    username: "henry_harris",
    email: "henry.harris@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+62-361-555-0115",
    address: {
      streetAddress: "21 Beach Road",
      city: "Bali",
      pincode: "80361",
      landmark: "Near Seminyak Beach",
    },
  },
  {
    username: "harper_martin",
    email: "harper.martin@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-403-555-0116",
    address: {
      streetAddress: "63 Mountain Avenue",
      city: "Banff",
      pincode: "T1L",
      landmark: "Near Banff National Park",
    },
  },
  {
    username: "alexander_thompson",
    email: "alexander.thompson@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-305-555-0117",
    address: {
      streetAddress: "95 Ocean Drive",
      city: "Miami",
      pincode: "33139",
      landmark: "Near South Beach",
    },
  },
  {
    username: "evelyn_garcia",
    email: "evelyn.garcia@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+66-76-555-0118",
    address: {
      streetAddress: "38 Tropical Road",
      city: "Phuket",
      pincode: "83110",
      landmark: "Near Patong Beach",
    },
  },
  {
    username: "daniel_martinez",
    email: "daniel.martinez@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+44-145-555-0119",
    address: {
      streetAddress: "15 Highland Road",
      city: "Scottish Highlands",
      pincode: "PH33",
      landmark: "Near Loch Ness",
    },
  },
  {
    username: "ella_robinson",
    email: "ella.robinson@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+971-4-555-0120",
    address: {
      streetAddress: "72 Desert Road",
      city: "Dubai",
      pincode: "00000",
      landmark: "Near Downtown Dubai",
    },
  },
  {
    username: "michael_clark",
    email: "michael.clark@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-406-555-0121",
    address: {
      streetAddress: "29 Pine Road",
      city: "Montana",
      pincode: "59001",
      landmark: "Near Yellowstone",
    },
  },
  {
    username: "grace_lewis",
    email: "grace.lewis@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+30-210-555-0122",
    address: {
      streetAddress: "51 Island Avenue",
      city: "Mykonos",
      pincode: "84600",
      landmark: "Near Mykonos Windmills",
    },
  },
  {
    username: "sebastian_walker",
    email: "sebastian.walker@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+506-555-0123",
    address: {
      streetAddress: "84 Forest Road",
      city: "Costa Rica",
      pincode: "10101",
      landmark: "Near Manuel Antonio",
    },
  },
  {
    username: "chloe_hall",
    email: "chloe.hall@example.com",
    password: "Password@123",
    role: "USER",
    phoneNumber: "+1-843-555-0124",
    address: {
      streetAddress: "37 Garden Street",
      city: "Charleston",
      pincode: "29401",
      landmark: "Near Historic Downtown",
    },
  },
  {
    username: "william_allen",
    email: "william.allen@example.com",
    password: "Password@123",
    role: "ADMIN",
    phoneNumber: "+81-3-555-0125",
    address: {
      streetAddress: "19 Shibuya Avenue",
      city: "Tokyo",
      pincode: "150-0002",
      landmark: "Near Shibuya Crossing",
    },
  },
];

module.exports = { data: sampleUsers };