const mongoose = require("mongoose");
const { ObjectId } = mongoose.Types;

const sampleMenuItems = [
  // Malibu Coastal Kitchen
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff39"),
    name: "Classic Cheeseburger",
    description: "Grilled beef patty with cheddar cheese, lettuce, tomato, onion, and house sauce.",
    price: 12.99,
    discountedPrice: 10.99,
    category: "Burgers",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff39"),
    name: "Grilled Salmon",
    description: "Fresh salmon fillet grilled with herbs and served with seasonal vegetables.",
    price: 18.99,
    discountedPrice: null,
    category: "Main Course",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff39"),
    name: "Caesar Salad",
    description: "Crisp romaine lettuce with parmesan, croutons, and Caesar dressing.",
    price: 8.99,
    discountedPrice: 7.49,
    category: "Salads",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1546793665-c74683f339c1",
    isAvailable: true,
  },

  // Broadway Spice House
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3a"),
    name: "Butter Chicken",
    description: "Tender chicken cooked in a rich tomato, butter, and cream-based Indian gravy.",
    price: 15.99,
    discountedPrice: 13.99,
    category: "Main Course",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3a"),
    name: "Vegetable Hakka Noodles",
    description: "Stir-fried noodles tossed with fresh vegetables and Asian sauces.",
    price: 11.99,
    discountedPrice: null,
    category: "Noodles",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3a"),
    name: "Thai Green Curry",
    description: "Aromatic Thai green curry with vegetables, coconut milk, and fragrant herbs.",
    price: 14.49,
    discountedPrice: null,
    category: "Thai",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd",
    isAvailable: true,
  },

  // Mountain Hearth
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3b"),
    name: "Wood-Fired Pasta",
    description: "Handmade pasta tossed in a rich tomato sauce with herbs and parmesan.",
    price: 14.99,
    discountedPrice: null,
    category: "Pasta",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3b"),
    name: "Mountain Steak",
    description: "Juicy grilled steak served with roasted vegetables and house sauce.",
    price: 22.99,
    discountedPrice: 19.99,
    category: "Main Course",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3b"),
    name: "Mushroom Risotto",
    description: "Creamy Italian risotto prepared with mushrooms, parmesan, and herbs.",
    price: 15.49,
    discountedPrice: null,
    category: "Rice",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
    isAvailable: true,
  },

  // La Tavola Fiorentina
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3c"),
    name: "Spaghetti Carbonara",
    description: "Classic Italian pasta with egg, parmesan, black pepper, and crispy pancetta.",
    price: 16.99,
    discountedPrice: null,
    category: "Pasta",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3c"),
    name: "Margherita Pizza",
    description: "Traditional pizza topped with tomato, mozzarella, and fresh basil.",
    price: 13.99,
    discountedPrice: 11.99,
    category: "Pizza",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3c"),
    name: "Tiramisu",
    description: "Classic Italian dessert made with mascarpone, coffee-soaked ladyfingers, and cocoa.",
    price: 7.99,
    discountedPrice: null,
    category: "Desserts",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9",
    isAvailable: true,
  },

  // Forest & Fork
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3d"),
    name: "BBQ Bacon Burger",
    description: "Beef burger topped with crispy bacon, cheddar cheese, and smoky BBQ sauce.",
    price: 14.99,
    discountedPrice: 12.99,
    category: "Burgers",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1553979459-d2229ba7433b",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3d"),
    name: "Chicken Tacos",
    description: "Soft tortillas filled with grilled chicken, lettuce, salsa, and fresh avocado.",
    price: 11.49,
    discountedPrice: null,
    category: "Tacos",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3d"),
    name: "Loaded Nachos",
    description: "Crispy tortilla chips loaded with cheese, jalapenos, salsa, and sour cream.",
    price: 9.99,
    discountedPrice: null,
    category: "Starters",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d",
    isAvailable: true,
  },

  // Caribbean Breeze
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3e"),
    name: "Caribbean Fish Tacos",
    description: "Fresh grilled fish served in soft tortillas with tropical salsa.",
    price: 14.99,
    discountedPrice: 12.99,
    category: "Tacos",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3e"),
    name: "Shrimp Rice Bowl",
    description: "Seasoned shrimp served with rice, vegetables, and tropical sauce.",
    price: 16.49,
    discountedPrice: null,
    category: "Rice Bowls",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1516685018646-549198525c1b",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3e"),
    name: "Mango Salsa",
    description: "Fresh mango, tomato, onion, lime, and herbs served as a refreshing side.",
    price: 6.49,
    discountedPrice: null,
    category: "Sides",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    isAvailable: true,
  },

  // Lakeside Grill
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3f"),
    name: "Smoky BBQ Ribs",
    description: "Slow-cooked pork ribs glazed with smoky homemade barbecue sauce.",
    price: 21.99,
    discountedPrice: 18.99,
    category: "BBQ",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3f"),
    name: "Grilled Chicken Plate",
    description: "Herb-marinated grilled chicken served with vegetables and fries.",
    price: 15.99,
    discountedPrice: null,
    category: "Main Course",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff3f"),
    name: "Coleslaw",
    description: "Fresh crunchy cabbage and carrot salad with creamy dressing.",
    price: 4.99,
    discountedPrice: null,
    category: "Sides",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1625938145744-e380515399bf",
    isAvailable: true,
  },

  // Hollywood Bites
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff40"),
    name: "Hollywood Burger",
    description: "Double beef burger with cheddar, lettuce, tomato, onion, and special sauce.",
    price: 15.99,
    discountedPrice: 13.99,
    category: "Burgers",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff40"),
    name: "Loaded Fries",
    description: "Crispy fries topped with melted cheese, jalapenos, and ranch sauce.",
    price: 8.99,
    discountedPrice: null,
    category: "Sides",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff40"),
    name: "Beef Tacos",
    description: "Seasoned beef tacos topped with lettuce, tomato, cheese, and salsa.",
    price: 12.49,
    discountedPrice: null,
    category: "Tacos",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85",
    isAvailable: true,
  },

  // Alpine Table
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff41"),
    name: "Swiss Cheese Fondue",
    description: "Traditional melted Swiss cheese served with fresh bread for dipping.",
    price: 18.99,
    discountedPrice: 16.99,
    category: "Swiss",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff41"),
    name: "Chicken Schnitzel",
    description: "Crispy breaded chicken served with roasted potatoes and salad.",
    price: 17.49,
    discountedPrice: null,
    category: "Main Course",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1599927987801-5d3f0c3e3d2e",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff41"),
    name: "Apple Strudel",
    description: "Warm apple pastry with cinnamon and a light dusting of sugar.",
    price: 7.49,
    discountedPrice: null,
    category: "Desserts",
    isPerishable: false,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1535920527002-b35e96722eb9",
    isAvailable: true,
  },

  // Savanna Kitchen
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff42"),
    name: "African BBQ Chicken",
    description: "Grilled chicken marinated in aromatic African spices and herbs.",
    price: 15.99,
    discountedPrice: 13.99,
    category: "BBQ",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff42"),
    name: "Beef Skewers",
    description: "Tender grilled beef skewers seasoned with traditional spices.",
    price: 17.49,
    discountedPrice: null,
    category: "Grills",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff42"),
    name: "Spiced Vegetable Stew",
    description: "Slow-cooked vegetables with aromatic spices and rich tomato sauce.",
    price: 10.99,
    discountedPrice: null,
    category: "Stews",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    isAvailable: true,
  },

  // Canal Bistro
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff43"),
    name: "Dutch Beef Steak",
    description: "Tender grilled beef steak served with roasted vegetables and potatoes.",
    price: 21.99,
    discountedPrice: 18.99,
    category: "Main Course",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff43"),
    name: "French Onion Soup",
    description: "Classic caramelized onion soup topped with toasted bread and melted cheese.",
    price: 8.99,
    discountedPrice: null,
    category: "Soups",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff43"),
    name: "Dutch Apple Pie",
    description: "Traditional apple pie with cinnamon and a buttery pastry crust.",
    price: 7.49,
    discountedPrice: null,
    category: "Desserts",
    isPerishable: false,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1562007908-17c67e878c88",
    isAvailable: true,
  },

  // Island Spice
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff44"),
    name: "Fijian Coconut Curry",
    description: "Creamy coconut curry prepared with vegetables and island spices.",
    price: 13.99,
    discountedPrice: 11.99,
    category: "Curries",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff44"),
    name: "Island Grilled Fish",
    description: "Fresh local fish grilled with tropical herbs and lemon.",
    price: 18.49,
    discountedPrice: null,
    category: "Seafood",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff44"),
    name: "Tropical Fruit Bowl",
    description: "Fresh seasonal tropical fruits served chilled.",
    price: 6.99,
    discountedPrice: null,
    category: "Desserts",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea",
    isAvailable: true,
  },

  // Cotswold Country Kitchen
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff45"),
    name: "Fish and Chips",
    description: "Crispy battered fish served with golden chips and tartar sauce.",
    price: 15.99,
    discountedPrice: 13.99,
    category: "British",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1579208030886-b937da0925dc",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff45"),
    name: "Shepherd's Pie",
    description: "Traditional British pie made with seasoned minced meat and creamy mashed potatoes.",
    price: 14.49,
    discountedPrice: null,
    category: "Main Course",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff45"),
    name: "Sticky Toffee Pudding",
    description: "Warm sponge pudding served with rich toffee sauce.",
    price: 7.99,
    discountedPrice: null,
    category: "Desserts",
    isPerishable: false,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307",
    isAvailable: true,
  },

  // Beacon Street Café
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff46"),
    name: "Cappuccino",
    description: "Freshly brewed espresso topped with steamed milk and creamy foam.",
    price: 4.49,
    discountedPrice: null,
    category: "Beverages",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1534778101976-62847782c213",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff46"),
    name: "Avocado Toast",
    description: "Toasted artisan bread topped with creamy avocado, herbs, and seeds.",
    price: 8.99,
    discountedPrice: 7.99,
    category: "Breakfast",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff46"),
    name: "Blueberry Muffin",
    description: "Freshly baked soft muffin packed with juicy blueberries.",
    price: 3.99,
    discountedPrice: null,
    category: "Bakery",
    isPerishable: false,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35",
    isAvailable: true,
  },

  // Bali Garden
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff47"),
    name: "Nasi Goreng",
    description: "Indonesian fried rice with vegetables, spices, and a flavorful sweet soy sauce.",
    price: 12.99,
    discountedPrice: 10.99,
    category: "Rice",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff47"),
    name: "Grilled Prawns",
    description: "Fresh prawns grilled with garlic, lime, and Indonesian spices.",
    price: 17.99,
    discountedPrice: null,
    category: "Seafood",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff47"),
    name: "Gado-Gado",
    description: "Traditional Indonesian vegetable salad served with rich peanut sauce.",
    price: 9.49,
    discountedPrice: null,
    category: "Salads",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    isAvailable: true,
  },

  // Banff Mountain Grill
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff48"),
    name: "Canadian Beef Burger",
    description: "Grilled Canadian beef patty with cheddar, lettuce, tomato, and house sauce.",
    price: 14.99,
    discountedPrice: 12.99,
    category: "Burgers",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff48"),
    name: "Maple BBQ Chicken",
    description: "Grilled chicken glazed with sweet maple barbecue sauce.",
    price: 16.49,
    discountedPrice: null,
    category: "BBQ",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff48"),
    name: "Poutine",
    description: "Crispy fries topped with cheese curds and rich gravy.",
    price: 8.99,
    discountedPrice: null,
    category: "Sides",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877",
    isAvailable: true,
  },

  // Ocean Drive Kitchen
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff49"),
    name: "Miami Shrimp Tacos",
    description: "Grilled shrimp tacos with cabbage, avocado, salsa, and lime crema.",
    price: 14.99,
    discountedPrice: 12.99,
    category: "Tacos",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff49"),
    name: "Cuban Sandwich",
    description: "Pressed sandwich with roasted pork, ham, Swiss cheese, pickles, and mustard.",
    price: 13.49,
    discountedPrice: null,
    category: "Sandwiches",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1553909489-cd47e0907980",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff49"),
    name: "Mango Smoothie",
    description: "Refreshing tropical smoothie made with fresh mango and yogurt.",
    price: 5.99,
    discountedPrice: null,
    category: "Beverages",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1505252585461-04db1eb84625",
    isAvailable: true,
  },

  // Phuket Thai Garden
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4a"),
    name: "Pad Thai",
    description: "Classic Thai rice noodles stir-fried with vegetables, peanuts, and tamarind sauce.",
    price: 12.99,
    discountedPrice: 10.99,
    category: "Noodles",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1559314809-0d155014e29e",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4a"),
    name: "Thai Basil Chicken",
    description: "Stir-fried chicken with Thai basil, chili, garlic, and fragrant spices.",
    price: 14.49,
    discountedPrice: null,
    category: "Main Course",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4a"),
    name: "Mango Sticky Rice",
    description: "Sweet sticky rice served with fresh mango and coconut cream.",
    price: 7.99,
    discountedPrice: null,
    category: "Desserts",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1626074353765-517a681e40be",
    isAvailable: true,
  },

  // Highland Hearth
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4b"),
    name: "Scottish Beef Stew",
    description: "Slow-cooked beef stew with root vegetables and rich Scottish gravy.",
    price: 15.99,
    discountedPrice: 13.99,
    category: "Stews",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4b"),
    name: "Haggis with Mash",
    description: "Traditional Scottish haggis served with creamy mashed potatoes and vegetables.",
    price: 16.49,
    discountedPrice: null,
    category: "Scottish",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4b"),
    name: "Shortbread",
    description: "Traditional Scottish buttery shortbread cookies.",
    price: 4.99,
    discountedPrice: null,
    category: "Desserts",
    isPerishable: false,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35",
    isAvailable: true,
  },

  // Desert Rose Kitchen
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4c"),
    name: "Chicken Shawarma",
    description: "Tender spiced chicken served with pita, vegetables, and garlic sauce.",
    price: 12.99,
    discountedPrice: 10.99,
    category: "Middle Eastern",
    isPerishable: true,
    foodType: "NON-VEG",
    imageUrl: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4c"),
    name: "Hummus Platter",
    description: "Creamy hummus served with warm pita bread and fresh vegetables.",
    price: 8.49,
    discountedPrice: null,
    category: "Starters",
    isPerishable: true,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1577805947697-89e18249d767",
    isAvailable: true,
  },
  {
    restaurantId: new ObjectId("6aa2ebcf8e3233809a86ff4c"),
    name: "Baklava",
    description: "Traditional Middle Eastern pastry layered with nuts, honey, and flaky pastry.",
    price: 6.99,
    discountedPrice: null,
    category: "Desserts",
    isPerishable: false,
    foodType: "VEG",
    imageUrl: "https://images.unsplash.com/photo-1519676867240-f03562e64548",
    isAvailable: true,
  },
];

module.exports = { data: sampleMenuItems };